//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellToMi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxtAd
    {
        public TxtAd()
        {
            this.TxtAdCategory = new HashSet<TxtAdCategory>();
            this.TxtAdPhoto = new HashSet<TxtAdPhoto>();
        }
    
        public string Email { get; set; }
        public int AdId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string FileLocation { get; set; }
        public string DateCreated { get; set; }
        public string DateUpdated { get; set; }
        public string Tags { get; set; }
        public string Approved { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<TxtAdCategory> TxtAdCategory { get; set; }
        public virtual TxtAdInfo TxtAdInfo { get; set; }
        public virtual ICollection<TxtAdPhoto> TxtAdPhoto { get; set; }
    }
}
