//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellToMi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxtAdInfo
    {
        public int AdId { get; set; }
        public string Price { get; set; }
        public string Qty { get; set; }
        public string Tax { get; set; }
        public string Shipping { get; set; }
        public string PaymentTerms { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string RefundPolicy { get; set; }
        public string DateCreated { get; set; }
        public string DateUpdated { get; set; }
    
        public virtual TxtAd TxtAd { get; set; }
    }
}
