//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellToMi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxtAdCategory
    {
        public int CategoryId { get; set; }
        public int AdId { get; set; }
    
        public virtual TxtAd TxtAd { get; set; }
    }
}
