//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellToMi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TxtAdPhoto
    {
        public string Email { get; set; }
        public int AdId { get; set; }
        public string FileLocation { get; set; }
        public string DateCreated { get; set; }
        public string DateUpdated { get; set; }
    
        public virtual TxtAd TxtAd { get; set; }
    }
}
